require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
    TargetRubyVersion: 3.2.2
    NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
