databases:
  - name: test_for_codica
    databaseName: test_for_codica
    user: test_for_codica

services:
  - type: web
    name: test_for_codica
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test_for_codica
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_BUCKETNAME
        sync: false
