default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", 'postgres') %>
  password: <%= ENV.fetch("DB_PASSWORD", 'postgres') %>

development:
  <<: *default
  database: TestForCodica_development

test:
  <<: *default
  database: TestForCodica_test

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", nil) %>
  database: TestForCodica_production
